import Head from "next/head";
import { Inter } from "@next/font/google";
import HeroSection from "@/Components/HeroSection";
import Content1 from "@/Components/Content1";
import Courses from "./courses";
import Content4 from "@/Components/Content4";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Panaver Dao Syllabus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroSection />
        <Content1 />
        <Courses />
        <Content4 />
      </main>
    </>
  );
}
