export const content3Data = [
  {
    txt1: "Web 3.0",
    txt2: "(Blockchain) and Metaverse Specialization",
    txt3: "This Web 3.0 and Metaverse specialization focuses on developing full-stack Web 3.0 and Metaverse experiences for the next generation of the internet by specializing in building worlds that merge the best of cutting-edge decentralized distributed blockchains with 3D metaverse client experiences.",
    H1: "Quarter IV",
    H2: "W3-351: Developing Smart Contracts and Planet-Scale Web 3.0 Dapps",
    img1: "https://editor.analyticsvidhya.com/uploads/842031-6.jpg",
    img2: "https://www.antiersolutions.com/wp-content/uploads/2022/10/image_2022_09_30T10_50_44_573Z.png",
    img3: "https://assets.entrepreneur.com/content/3x2/2000/1653296515-Untitleddesign98.jpg",
    H3: "Quarter V",
    H4: "MV-361: Developing Planet-Scale Open Virtual and Augmented Metaverse Experiences",
  },

  {
    txt1: "Artificial Intelligence",
    txt2: "(AI) and Deep Learning Specialization",
    txt3: "The AI and Deep Learning specialization focuses on building and deploying intelligent APIs using OpenAI models and building custom Deep Learning Tensorflow models.",
    H1: "Quarter IV",
    H2: "AI-351: Developing Planet-Scale Intelligent APIs and Python Programming",
    img1: "https://www.cmrit.ac.in/wp-content/uploads/2021/06/cmr.jpg",
    img2: "https://cdn.sanity.io/images/f1avhira/production/414320c33b8ad1ba1c397d58ab166105b5737241-2400x1260.png",
    img3: "https://valohai.com/blog/dlops/ml-vs-dl.png",
    H3: "Quarter V",
    H4: "AI-361: Deep Learning and MLOps",
  },

  {
    txt1: "Cloud-Native",
    txt2: "Computing Specialization",
    txt3: "The Cloud-Native Computing Specialization focuses on Containers, Kubernetes, and CDK for Kubernetes.",
    H1: "Quarter IV",
    H2: "CN-351: Certified Kubernetes Application Developer (CKAD)",
    img1: "https://walkingtree.tech/wp-content/uploads/2020/12/The-rise-of-Cloud-Native-Computing.jpg",
    img2: "https://miro.medium.com/max/1400/1*TwHbkDlsFWrTOEpOrRDKfw.png",
    img3: "https://www.datocms-assets.com/2885/1600069441-375a619c-d286-47d4-ba36-c1025e7e1d60.png",
    H3: "Quarter V",
    H4: "CN-361: Developing Multi-Cloud APIs using CDK for Terraform",
  },
  {
    txt1: "Ambient Computing",
    txt2: "and IoT Specialization",
    txt3: "The Ambient Computing and IoT Specialization focuses on building Smart Homes, Offices, Factories, and Cities using Voice computing, Matter Protocol, and Embedded Devices.",
    H1: "Quarter IV",
    H2: "AC-351: Ambient Computing with Voice Assistants and Matter Protocol Devices",
    img1: "https://www.infosys.com/content/dam/infosys-web/en/insights/Images/ambient-technology.JPG",
    img2: "https://pub.mdpi-res.com/electronics/electronics-10-00980/article_deploy/html/images/electronics-10-00980-g001.png?1618906866",
    img3: "https://tweedegolf.nl/images/rustvsc.png",
    H3: "Quarter V",
    H4: "AC-361: Embedded Programming using C and Rust",
  },
  {
    txt1: "Genomics",
    txt2: "and Bioinformatics Specialization",
    txt3: "Genomics is the study of the total genetic makeup of individual organisms, and how this genetic information is structured, functions, and has evolved; bioinformatics encompasses a diverse range of analytical methods and tools applied to genomic data. This Specialization focuses on performing complex bioinformatics analysis using the most essential Python libraries and applications.",
    H1: "Quarter IV",
    H2: "Bio-351: Python for Biologists",
    img1: "https://www.csb.pitt.edu/wp-content/uploads/2014/01/Genomics.png",
    img2: "https://pbs.twimg.com/media/FhuuU5uWYAIuvr8?format=jpg&name=large",
    img3: "https://cdn.eduonix.com/assets/images/header_img/2021031510262012793.png",
    H3: "Quarter V",
    H4: "Bio-361: Bioinformatics with Python",
  },
  {
    txt1: "Network Programmability",
    txt2: "and Automation Specialization",
    txt3: "More than ever, network engineers are finding it challenging to complete their duties entirely manually. Network automation is now crucial due to new protocols, technologies, delivery models, and the requirement for enterprises to become more adaptable and agile. This course teaches network engineers how to automate systems with code using a variety of technologies and tools, including Linux, Python, APIs, and Git.",
    H1: "Quarter IV",
    H2: "NPA-351: CCNA 200-301 Certification",
    img1: "https://codingnetworks.blog/wp-content/uploads/2020/07/network-programability-automation-banner-1080x390.jpg",
    img2: "https://i.ytimg.com/vi/dKF0W1MJI2g/maxresdefault.jpg",
    img3: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS44tzukLzAKPW4fCD9VFIcN3ngcux1kQjwj_q2LX1PsCirt7rzrLkQTvY3C3D9mZa1Gfk&usqp=CAU",
    H3: "Quarter V",
    H4: "NPA-361: Network Programmability and Automation",
  },
];
